In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
import numpy as np

In [2]:
# This file contains a series of financial and macroeconomic outcome variables.
macro = pd.read_csv("../data3/macro.csv", index_col=0)

mret = macro[['indprol1']]
mret.tail()
# mret.plot()

            indprol1
date
2020-08-01 -0.000456
2020-09-01  0.006083
2020-10-01  0.004420
2020-11-01  0.011487
2020-12-01  0.008215

In [3]:
# This file contains labeled attention to topics from structureofnews.com

topics = pd.read_csv("../data3/topics.csv", index_col=0)
topics.tail()

,Natural disasters,Internet,Soft drinks,Mobile devices,Profits,M&A,Changes,Police/crime,Research,Executive pay,...,European politics,Size,NASD,Mexico,Retail,Long/short term,Wide range,Lawsuits,UK,Revenue growth
date,,,,,,,,,,,,,,,,,,,,,
2017-02-01,0.005041,0.010796,0.004336,0.009094,0.004619,0.003726,0.006224,0.011012,0.006346,0.004761,...,0.011896,0.005128,0.003284,0.007718,0.004835,0.005311,0.004215,0.005482,0.003075,0.006990
2017-03-01,0.006498,0.011357,0.003211,0.007999,0.003005,0.003417,0.006758,0.011267,0.005931,0.004582,...,0.014791,0.005581,0.002946,0.004698,0.005293,0.005542,0.004170,0.004596,0.004484,0.005598
2017-04-01,0.006052,0.010458,0.003448,0.007871,0.004473,0.003301,0.006595,0.010880,0.006122,0.004075,...,0.020162,0.006293,0.003023,0.004557,0.005231,0.004725,0.004145,0.005918,0.002775,0.005881
2017-05-01,0.005192,0.009293,0.003597,0.007684,0.003389,0.003350,0.006191,0.012366,0.006202,0.003481,...,0.013386,0.005571,0.002984,0.004510,0.006182,0.005368,0.004217,0.004596,0.003356,0.005258
2017-06-01,0.006807,0.012327,0.002527,0.009575,0.001858,0.004042,0.006155,0.013799,0.004839,0.003334,...,0.016046,0.005707,0.003476,0.004613,0.007563,0.005004,0.004559,0.004741,0.004814,0.005598

In [4]:
# Restrict both datasets to overlapping dates
common_dates = macro.index.intersection(topics.index)

macro = macro.loc[common_dates]
topics = topics.loc[common_dates]

print(f"Overlapping period: {common_dates[0]} → {common_dates[-1]}  ({len(common_dates)} months)")

Overlapping period: 1984-01-01 → 2017-06-01  (402 months)

In [5]:
articles = pd.read_parquet("../data3/articles.pq")
articles.head()

,accession_number,display_date,headline
0,19840102000129,1984-01-02 07:00:00,Portfolio Managers See Overseas Stocks Climbin...
1,19840117000049,1984-01-17 07:00:00,Four Big Banks Had Profit Gains In 4th Period ...
2,19840117000136,1984-01-17 07:00:00,World Brief: U.S. and Common Market Sign Accor...
3,19840117000164,1984-01-17 07:00:00,Speaking of Business: Consumers May Be Becomin...
4,19840123000136,1984-01-23 07:00:00,Dollar Moves Up On Rise in GNP; Gold Weakens -...

---
# 3.a